# Generated by Django 4.1.1 on 2022-09-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
    ]
