# Generated by Django 4.1.1 on 2022-09-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_department_id_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='departments',
        ),
    ]
